baseURL = 'https://supertsumu.github.io/'
languageCode = 'en-us'
title = 'SuperTsumu'
uglyURLs = false
canonifyURLs = true
enableRobotsTXT = false

theme = "hugo-theme-shell"

[markup.goldmark.renderer]
unsafe = true